title: Dealbot
email: dealbot@faraday.io
description: > # this means to ignore newlines until "baseurl:"
  Lightweight open-source sales automation for Pipedrive from Faraday
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dealbot.faraday.io" # the base hostname & protocol for your site
twitter_username: faradayio
github_username:  faradayio
permalink: /:slug

# Build settings
markdown: kramdown
highlighter: rouge